### ISSUE TITLE
[User] Final confirmation of reservation for set course is still English 

### ISSUE THREAD

**Issue by GochaLearningSpace** [Willings-Inc/SCG#125]
https://docs.google.com/spreadsheets/d/1DDN2HUTOTrrCNXjgKiMve65L0Xe9WsANkdFNXttH8lw/edit#gid=705820224&range=J15

**Comment by ShivomA** [comment]
@GochaLearningSpace confirmed this in the production link (attached ss)
<img width="966" alt="image" src="https://user-images.githubusercontent.com/59804849/235340170-c76931c7-6238-46e8-9c36-bd0389df5c1c.png">

Closing this one
