### ISSUE TITLE
[User] In the Course selection, "Full Bidy oil course" is not shown. 

### ISSUE THREAD

**Issue by GochaLearningSpace** [Willings-Inc/SCG#126]
https://docs.google.com/spreadsheets/d/1DDN2HUTOTrrCNXjgKiMve65L0Xe9WsANkdFNXttH8lw/edit#gid=705820224&range=M16

**Comment by ShivomA** [comment]
@GochaLearningSpace full body oil course is displayed for selection, confirm attached ss. (As I used google translation the exact sentence may not match)
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/59804849/235339894-0212e4ad-062c-45c0-83c3-592dd93ea570.png">

<img width="343" alt="image" src="https://user-images.githubusercontent.com/59804849/235339910-50f0d108-ba1f-40c7-a5a1-8e4e706e86f5.png">

Closing the issue
