### ISSUE TITLE
[User] Description not displayed correctly on booking confirmation page

### ISSUE THREAD

**Issue by amanscisingh** [Willings-Inc/SCG#144]
@GochaLearningSpace please see this ss. 
![image](https://user-images.githubusercontent.com/68449680/219824117-0503de61-e23f-493d-999e-fe5c4d1b7700.png)

**Comment by ShivomA** [comment]
@GochaLearningSpace 
Closing the issue as reflected in the production link
<img width="976" alt="image" src="https://user-images.githubusercontent.com/59804849/235339776-0d22e874-4307-4eb1-87bc-7dc30c3cd575.png">
