### ISSUE TITLE
Fix , login related issues. 

### ISSUE THREAD

**Issue by GochaLearningSpace** [Willings-Inc/SCG#148]
@Anu8690 @amanscisingh @Sau1503k @ShivomA 
Please fix below issues.

https://takashiichima-af82034.slack.com/archives/C030ED386S3/p1677932420676039

**Comment by ShivomA** [comment]
@GochaLearningSpace 
Closing the issue as the user can see the "email already exist" notification. And new issue is created to address the phone number input problem
