### ISSUE TITLE
[Admin] we cannot gather any data from sales management.

### ISSUE THREAD

**Issue by GochaLearningSpace** [Willings-Inc/SCG#160]
We cannot retrieve sales data from sales management in admin.
[2023-04-27 05-14-19.zip](https://github.com/Willings-Inc/SCG/files/11342300/2023-04-27.05-14-19.zip)

**Comment by Anu8690** [comment]
@GochaLearningSpace we do not get any data from sales management is because no code is implemented for that. It needs to be implemented. For this we need to ask customer whatv all functionalities he needs in sales management.
