### ISSUE TITLE
Coupon Code [QOHS50] is not reflected.

### ISSUE THREAD

**Issue by GochaLearningSpace** [Willings-Inc/SCG#164]

**Comment by GochaLearningSpace** [comment]
![image](https://user-images.githubusercontent.com/6176526/236024793-0006becc-e865-4469-af05-2812b14e7e8b.png)

**Comment by Anu8690** [comment]
Because @GochaLearningSpace it is expired. If you want I can extend its expiry date.
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/64983435/236637029-1b6b0446-aa38-483d-b64b-1cd3bd1c95f3.png">

**Comment by GochaLearningSpace** [comment]
@Anu8690 CC: @amanscisingh @Sau1503k @ShivomA 
Agreed with customer that current solution works fine. Closed
