### ISSUE TITLE
MacBook Safari , email address registration. cannot login 

### ISSUE THREAD

**Issue by GochaLearningSpace** [Willings-Inc/SCG#171]
https://user-images.githubusercontent.com/6176526/236626788-1005ebfc-837d-4953-9af0-2e0caf5ac317.mov

**Comment by Anu8690** [comment]
Solved @GochaLearningSpace . @amanscisingh Please pull the latest changes in netlify.

**Comment by Anu8690** [comment]
@amanscisingh PLease provide with netlify credentials.

**Comment by amanscisingh** [comment]
@Anu8690 I have pulled the changes and updated on netlify
Netlify Credentials: saswatiisabella2002@gmail.com
Password : QOHS_PROD1234
