### ISSUE TITLE
Admin Screen, the last day of the month will not be shown in therapist administration screen in admin system

### ISSUE THREAD

**Issue by GochaLearningSpace** [Willings-Inc/SCG#189]
@ShivomA please investigate this one, for example, June 30th or July 31th is not shown in admin screen. 

![admin_end-date-willnotbe-shown](https://github.com/Willings-Inc/SCG/assets/6176526/f8bfd7c2-5cea-4437-93e1-29d573536c4d)

**Comment by GochaLearningSpace** [comment]
@ShivomA , @Anu8690  , can you investigate and fix this, if this takes time, let me know when you will be able to fix ?

**Comment by Anu8690** [comment]
@GochaLearningSpace san this issue is solved. I have updated the code in production. Please confirm.
