### ISSUE TITLE
Please include oil course (全身オイルコース) to the course selection

### ISSUE THREAD

**Issue by GochaLearningSpace** [Willings-Inc/SCG#94]
![Screenshot_20221002-135332](https://user-images.githubusercontent.com/6176526/193438960-0a629686-4a83-4934-a4fc-5236e91f685f.png)

**Comment by ShivomA** [comment]
@GochaLearningSpace confirmed in production link, closing the issue
<img width="946" alt="image" src="https://user-images.githubusercontent.com/59804849/235340257-f9bf01ae-63a4-4f90-91c7-91bdc3f94976.png">
